name: python3-on-wine-on-alpine
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.15
    steps:
      - name: print python version
        run: |
          python -V
          pyinstaller --version
