name: python3-on-wine-on-alpine
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: py3wine
          push: false

      - uses: addnab/docker-run-action@v3
        with:
          image: py3wine
          options: -v ${{ github.workspace }}:/src
          run: python -V
