name: python3-on-wine-on-alpine
on: push

jobs:
  push_to_registry:
    name: Push custom Docker image to GitHub Container Registry (ghcr.io)
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

