name: python3-on-wine-on-alpine
on: push

jobs:
  push_to_registry:
    name: Push custom Docker image to GitHub Container Registry (ghcr.io)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
          repository: shiny-comic/wine-py3-compiler
          tag_with_ref: true

